### ISSUE TITLE
Inkline

### ISSUE THREAD

**Issue by kaniak274** [team-yuml-kkks/YumlJira#11]
Maybe we should try Inkline for vue. I think it has good integration with bootstrap but this decision has to be made by you @KamilSupera. If you want to add this library just set it up inside our project.
https://inkline.io/

**Comment by KamilSupera** [comment]
@kaniak274 ok I will read about Inkline and decide

**Comment by KamilSupera** [comment]
I chose Bulma https://bulma.io/
