### ISSUE TITLE
Vue-Router

### ISSUE THREAD

**Issue by kaniak274** [team-yuml-kkks/YumlJira#4]
IMO we should use both SPA and MPA styles in this project. But we need still to configurate vue-router. What do you think @KamilSupera ? I think we should use API + vue for main template and just django for some others. (Maybe I will try make mobile version later).

**Comment by KamilSupera** [comment]
@kaniak274 What do you mean about mobile version? For me if we have Django like base so router section leave for Django.  Oh but if u want want use vue-router - ok im flex :D

**Comment by kaniak274** [comment]
I'm not sure maybe I will add mobile version (to train kotlin) of this app so I will need API to work with. And I think we should do a little both. For example for task / project section we should do vue router + django routing (no history, we have to add url to server as well) and for things like password change we could do normal django forms with crispy. There is also other thing what with login / logout. If we want to add API and axios to make API calls we need authorization so we have to setup login to return JWT token. Anyway we have to make decision what are we gonna do.
